### PR TITLE
Fix polkit permissions

### LINKED ISSUE #182: Couldn't get permission to set hostname
### What Happened?

Initial setup couldn't get permission to name this device

### Steps to Reproduce

Run through initial setup on the latest OS 8 daily

### Expected Behavior

Could get permission to set hostname

### OS Version

Early Access

### Software Version

Latest release (I have run all updates)

### Log Output

_No response_

### Hardware Info

_No response_

### PR DESCRIPTION
**Pull request by vjr**
Fixes #182 

I could be wrong but I vaguely recall that PKLA is deprecated probably gone with Noble hence replacing with PK rules fixes the issue for me.

Starting this draft, will mark for review after I test.

Feel free to (push commits) suggest any cleanups (especially whether checks for "local" and "active" are OK in addition to just user "lightdm") in the mean time.

### CODE REVIEW

**Comment by vjr** [comment]
https://github.com/elementary/initial-setup/pull/186 probably didn't have any effect, at least in in my testing while poking around looking at this issue.

**Comment by vjr** [comment]
Appears to be working for me although I've been testing haphazardly and not the "right way" [tm] by building an ISO and using that. At least it appears to fix the issue by getting past the initial-setup phase from what I can tell.

Please feel free to test along with review and please feel free to push to this PR any changes suggested or necessary because I might not be able to get back to this until next weekend, if at all :-)

**Review by lenemter — APPROVED** [review]
Fixes the issue for me! The Greeter is broken though, but it's another issue :)

**Comment by lenemter** [comment]
I can confirm the device name is set correctly. I'll merge this.

**Pull request merged**
