### PR TITLE
Added screenshots

### PR DESCRIPTION
**Pull request by Ananthavijay**
Fixes : https://github.com/elementary/initial-setup/issues/73

Added screenshot : 

screenshot@2x

Thank you

### CODE REVIEW

**Comment by ryonakano** [comment]
So the consequence would look like this:

```markdown
# Initial Setup
[![Translation status](https://weblate.elementary.io/widgets/installer/-/initial-setup/svg-badge.svg)](https://l10n.elementary.io/projects/installer/initial-setup/?utm_source=widget)

![screenshot@2x](https://user-images.githubusercontent.com/35162705/66404764-b4785880-ea06-11e9-8ebc-2eccce5bb92f.png)

An initial setup app to create new users

## Building, Testing, and Installation
…(some lines follow)
```

**Comment by Ananthavijay** [comment]
Yea I understood it before.. Wait for a min

**Comment by Ananthavijay** [comment]
Done @ryonakano

**Comment by ryonakano** [comment]
```markdown
# Initial Setup
[![Translation status](https://weblate.elementary.io/widgets/installer/-/initial-setup/svg-badge.svg)](https://l10n.elementary.io/projects/installer/initial-setup/?utm_source=widget)

An initial setup app to create new users

![screenshot@2x](https://user-images.githubusercontent.com/35162705/66404764-b4785880-ea06-11e9-8ebc-2eccce5bb92f.png)

## Building, Testing, and Installation
…(some lines follow)
```

@Ananthavijay My bad, I should quote an example that has both an app description and the screenshot. After searching for other repositories, I found it seems like we tend to bring the description above the screenshot. This might be a kind of nitpicking though. 🙇

**Comment by Ananthavijay** [comment]
Done @ryonakano ..  Sorry for taking more time

**Pull request merged**
