### PR TITLE
Set 24h format based on language

### LINKED ISSUE #70: German user accounts should use 24h time by default
On a fresh installation of Juno (stable), the wingpanel used AM/PM by default, even though I used German as my language/region during installation.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/64541582-german-user-accounts-should-use-24h-time-by-default?utm_campaign=plugin&utm_content=tracker%2F93529863&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F93529863&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by meisenzahl**
I'm working on a solution to resolve #70 

I still have to find a way to change the `GLib.Settings` for another user.

### CODE REVIEW

**Comment by danrabbit** [comment]
I guess it's probably a shorter list of locales that want 12 hrs than 24 hrs right?

And I think it's probably more highly correlated to physical location than language. For example for Spanish it appears that Spain would use 24hr but Mexico would use 12hr. From Wikipedia it looks like the list of 12-hr using countries are:

* The UK
* Ireland
* The US
* Canada (but not Quebec)
* Australia
* New Zealand
* India
* Pakistan
* Bangladesh
* Malaysia
* Malta
* Egypt
* Mexico
* Philippines

**Comment by meisenzahl** [comment]
The location is currently not configurable. Is this a design decision?

Is the time zone set based on the current location (`libgeoclue`)?

The time format could then be set automatically using the same logic.

**Comment by danrabbit** [comment]
No, it's just a missing feature. I agree we could have a screen to set the timezone and format and on this screen we could use GeoClue to try to guess defaults, but that depends on having working internet. so maybe we also need a screen to select a wireless network if internet is not already connected

**Comment by meisenzahl** [comment]
I added a screen to set the timezone. @danrabbit what's your opinion on setting the clock format based on timezone?

**Comment by meisenzahl** [comment]
[List of countries using 12 hour format](https://www.alanet.org/docs/default-source/default-document-library/cm01_international_etiquette.pdf)

@danrabbit I didn't find the link to the wikipedia article you mentioned. Could you provide the link for reference?

**Comment by tintou** [comment]
You don't need to hardcode the list of countries to get the 12h/24h, you can check if the current locale is using 12h by default by checking if `Posix.nl_langinfo (Posix.NLItem.T_FMT)` contains `%r` or `%l` or `%I`.

**Comment by meisenzahl** [comment]
@tintou thanks for your feedback. This allowed me to simplify the code.

**Comment by danrabbit** [comment]
@meisenzahl I guess what we probably want to do is write to accounts service and use the settings daemon to keep things in sync like we do with keyboard input methods

**Comment by meisenzahl** [comment]
`set_timezone ()`, `set_clock_format ()` and `set_keyboard_layout ()` in `MainWindow` should all be implemented as `async` methods. @danrabbit is there a common way in Vala to chain `async` methods?

**Comment by cassidyjames** [comment]
@meisenzahl could you resolve conflicts here?

**Comment by meisenzahl** [comment]
@cassidyjames done 🙂️

**Comment by marbetschar** [comment]
@meisenzahl any chance you  got some time you resolve the conflicts here ... again? :sweat_smile:

**Comment by meisenzahl** [comment]
@marbetschar done ✔️

**Comment by jeremypw** [comment]
> `set_timezone ()`, `set_clock_format ()` and `set_keyboard_layout ()` in `MainWindow` should all be implemented as `async` methods. @danrabbit is there a common way in Vala to chain `async` methods?

You can chain async methods by using the `yield` keyword.

**Comment by danrabbit** [comment]
@meisenzahl apologies for asking you to resolve conflicts here yet again :sweat_smile: Now that we have the network view merged this should be unblocked

**Comment by meisenzahl** [comment]
@danrabbit done :heavy_check_mark:

**Comment by danrabbit** [comment]
Pushed to a branch on the project so it's easier to collab: https://github.com/elementary/initial-setup/pull/142

**Pull request closed without merging**
